apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
      - name: hello1
        image: gcr.io/google-samples/hello-app:2.0

